[includes]
toml = ["radiopyo/basic_water_radiolysis.toml"]

#---------------- Example of pulsed beam defined with peak dose rate -------------------
[beam.constant]
dose_rate  = 1.58e3   # Peak dose rate for pulsed beam [Gy/s]
max_dose   = 2000e3   # Max Dose in [Gy]
LET        = 0.17   # [keV/µm] (6MeV electrons in water)

#---------------------- Definition of Constants concentrations -------------------------
[concentrations.fixed] # Unit is [mol]/[l]
H2O = 55
O2 = 250e-6
#----------------------- Definition of initial concentrations --------------------------
# Rem: if unspecified, initial cc are assumed 0 (except for constant species)    
[concentrations.initial] # Unit is [mol]/[l]
C7F15COO_minus = 2.42e-5
C8F17SO3_minus = 2.00e-5

# ----------------------------- PFAS related reactions ----------------------------- 
[[reactions.k_reaction]] 
reactants = ["e_aq", "C7F15COO_minus",]
products = ["C7F15COO_r_minus_minus",]
k_value = 5.1e7 #4.35e7

[[reactions.k_reaction]] 
reactants = ["e_aq", "C8F17SO3_minus",]
products = ["C8F17SO3_r_minus_minus",]
k_value = 5.1e7 #3.78e7

[[reactions.k_reaction]]  # 7) e_aq + H2O2 -> OH_minus + OH_r
reactants = ["e_aq", "H2O2",]
products = ["OH_minus", "OH_r",]
k_value = 1.1e10