[includes]
toml = ["radiopyo/basic_water_radiolysis.toml"]

#----------------------------------- BEAM Definition -----------------------------------
[[beam.constant]]
dose_rate = 1.58e3 # Peak dose rate for pulsed beam [Gy/s]
max_dose = 2000e3  # Max Dose in [Gy]
LET = 0.17         # [keV/µm] (6MeV electrons in water)

#---------------------- Definition of Constants concentrations -------------------------
[concentrations.fixed] # Unit is [mol]/[l]
H2O = 55
O2 = 250e-6

#----------------------- Definition of initial concentrations --------------------------
# Rem: if unspecified, initial cc are assumed 0 (except for constant species)    
[concentrations.initial] # Unit is [mol]/[l]
C7F15COO_minus = 2.42e-5 # --> 10 ppm
C8F17SO3_minus = 2.00e-5 # --> 10 ppm

# ----------------------------- PFAS related reactions ----------------------------- 
[[reactions.k_reaction]]
reaction = "e_aq + C7F15COO_minus -> C7F15COO_r_minus_minus"
k_value = 5.1e7

[[reactions.k_reaction]]
reaction = "e_aq + C8F17SO3_minus -> C8F17SO3_r_minus_minus"
k_value = 5.1e7

# Re-definition of H2O2 scavenge reaction by e_aq (from basic_water_radiolysis.toml)
[[reactions.k_reaction]]
reaction = "e_aq + H2O2 -> OH_minus + OH_r"
k_value = 1.1e10                            # 0 # -> To turn it off