[includes]
toml = "radiopyo/config_Labarbe.toml"


#---------------- Example of pulsed beam defined with peak dose rate -------------------
[[beam.pulsed]]
dose_rate_peak = 125       # Peak dose rate for pulsed beam [Gy/s]
on_time        = 8e-3      # Time [seconds] (used only for Pulsed beam)
period         = 200e-3    # Period [seconds]
max_dose       = 1
LET            = 7.5       # [keV/µm]

