[includes]
toml = "radiopyo/basic_water_radiolysis.toml"

#----------------------- Beams defined in N. Blond Master Thesis -----------------------
[[beam.constant]]
dose_rate = 0.13
max_dose = 32
LET = 0.27       # [keV/µm] -> 9MeV electrons

[[beam.pulsed]]
label = "O2_depletion"
dose_rate_peak = 319
period = 121
on_time = 0.1
n_pulse = 1
start_time = 30
LET = 0.27             # [keV/µm] -> 9MeV electrons

[[beam.constant]]
label = "O2_depletion_conv"
dose_rate_peak = 1
max_dose = 32
start_time = 30
LET = 0.27                  # [keV/µm] -> 9MeV electrons

[concentrations.fixed] # Unit is [mol]/[l]
H2O = 55

[concentrations.initial] # Unit is [mol]/[l]
O2 = 52e-6

# ----------------------------------------------------------------------------------
#                                ADAPTING K-REACTIONS                             
# ----------------------------------------------------------------------------------
[[reactions.k_reaction]]
reaction = "O_r_minus + O2 -> O3_minus"
k_value = 3.6e9                         #7.2e9                         #3.6e9

[[reactions.k_reaction]]
reaction = "H_r + O2 -> HO2_r"
k_value = 2.1e10               #4.2e10               #2.1e10

[[reactions.k_reaction]]
reaction = "e_aq + O2 -> O2_r_minus"
k_value = 1.9e10                     #0.48e10                    #1.9e10
